version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=2301967@sit.singaporetech.edu.sg
      - MYSQL_DB=mydb
    volumes:
      - ./backend:/app
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 2301967@sit.singaporetech.edu.sg
      MYSQL_USER: admin
      MYSQL_PASSWORD: 2301967@sit.singaporetech.edu.sg
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

  git:
    image: gitea/gitea:latest
    container_name: gitea
    restart: always
    environment:
      USER_UID: 1000
      USER_GID: 1000
    volumes:
      - ./gitea/data:/data
    ports:
      - "3000:3000"  # Gitea web UI
      - "2222:22"    # Gitea SSH (optional)
    depends_on:
      - db

volumes:
  dbdata:
